[package]
name = "arkanoo"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37", features = ["mixer", "ttf", "image"] }
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
