[package]
name = "arkanoo"
version = "0.4.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37", features = ["mixer", "ttf", "image"] }
rand = "0.8"
once_cell = "1.21.3"

[build-dependencies]
winres = "0.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
